export const ROUTES_PATH = {
  home: '/',
  dashboard: '/',
  allExams: '/exams',
  prizeQuizzes: '/exams/prize-quizzes',
  lms: '/lms',
  courses: '/lms/courses',
  courseware: '/lms/courseware',
  questions: '/questions',
  allQuestions: '/questions/all',
  addQuestion: '/questions/new',
  batchImport: '/questions/batch-import',
  importRecords: '/questions/import-records',
  students: '/students',
  allStudents: '/students/all',
  signupForms: '/students/signup-forms',
  studentSettings: '/students/settings',
  resultsDatabase: '/results-database',
  statistics: '/statistics',
  certificates: '/certificates',
  surveys: '/surveys',
  settings: '/settings',
  help: '/help',
  signIn: '/sign-in',
  signUp: '/sign-up',
} as const
