export const ROUTES_PATH = {
  lms: '/lms',
  help: '/help',
  dashboard: '/',
  signIn: '/sign-in',
  signUp: '/sign-up',
  allExams: '/exams',
  center: '/centers',
  surveys: '/surveys',
  students: '/students',
  settings: '/settings',
  courses: '/lms/courses',
  questions: '/questions',
  statistics: '/statistics',
  courseware: '/lms/courseware',
  certificates: '/certificates',
  addCenter: '/centers/new',
  addQuestion: '/questions/new',
  allStudents: '/students/all',
  allQuestions: '/questions/all',
  prizeQuizzes: '/exams/prize-quizzes',
  signupForms: '/students/signup-forms',
  studentSettings: '/students/settings',
  resultsDatabase: '/results-database',
  batchImport: '/questions/batch-import',
  importRecords: '/questions/import-records',
} as const
