export const ROUTES_PATH = {
  lms: '/lms',
  help: '/help',
  dashboard: '/',
  signIn: '/sign-in',
  signUp: '/sign-up',
  /** Public student registration (shareable invite URL). */
  studentJoin: '/join',
  /** Short interest form (name + phone) for Signup Forms inbox. */
  studentLeadJoin: '/join/lead',
  allExams: '/exams',
  examDetails: '/exams/:examId',
  studentExamPlayer: '/student/exam-player',
  center: '/centers',
  surveys: '/surveys',
  students: '/students',
  payments: '/payments',
  settings: '/settings',
  courses: '/lms/courses',
  questions: '/questions',
  statistics: '/statistics',
  courseware: '/lms/courseware',
  certificates: '/certificates',
  addCenter: '/centers/new',
  addQuestion: '/questions/new',
  editQuestion: '/questions/:questionId/edit',
  allStudents: '/students/all',
  allQuestions: '/questions/all',
  prizeQuizzes: '/exams/prize-quizzes',
  signupForms: '/students/signup-forms',
  studentSettings: '/students/settings',
  resultsDatabase: '/results-database',
  batchImport: '/questions/batch-import',
  importRecords: '/questions/import-records',
} as const
