export { AdminPage } from './AdminPage'
export { AddCenterPage } from './AddCenter'
export { AddQuestionPage } from './AddQuestionPage'
export { AllStudentsPage } from './AllStudentsPage'
export { CentersPage } from './Centers'
export { CoursesPage } from './CoursesPage'
export { DashboardPage } from './DashboardPage'
export { FeaturePage } from './FeaturePage/FeaturePage'
export { HomePage } from './HomePage'
export { PaymentsPage } from './PaymentsPage'
export { PrizeQuizzesPage } from './PrizeQuizzesPage'
export { QuestionsPage } from './QuestionsPage'
export { SignInPage, SignUpPage } from './Auth'
export { SignupFormsPage } from './SignupFormsPage'
export { StudentLeadSignupPage } from './StudentLeadSignupPage'
export { StatisticsPage } from './StatisticsPage'
