export { AdminPage } from './AdminPage'
export { AddCenterPage } from './AddCenter'
export { AddQuestionPage } from './AddQuestion'
export { AllStudentsPage } from './AllStudents'
export { CentersPage } from './Centers'
export { DashboardPage } from './Dashboard'
export { HomePage } from './HomePage'
export { PaymentsPage } from './Payments'
export { PrizeQuizzesPage } from './PrizeQuizzes'
export { QuestionsPage } from './Questions'
export { SignInPage, SignUpPage } from './Auth'
export { SignupFormsPage } from './SignupForms'
export { StudentLeadSignupPage } from './StudentLeadSignup'
export { StatisticsPage } from './Statistics'
